name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - run: npm install --only=prod
      - run: npm -g install jest@^24.0.0
        if: matrix.node-version == '8.x'
      - run: npm -g install jest@^27.0.0
        if: matrix.node-version != '8.x'
      - run: yarn install --ignore-engines
      - run: yarn add mock-fs@4 --ignore-engines -D
        if: matrix.node-version == '8.x'
      - run: npm run test:coverage
        env:
          CI: true
      - name: Send Report to Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
      - name: Send Parallel Finished
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
